services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=exam_prep_db

        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql

volumes:
    db_data:
